import { Category, Complexity, PricingTier, Workflow } from './types';

export const WORKFLOWS: Workflow[] = [
  {
    id: '1',
    title: 'Smart Resume Classifier',
    description: 'Automatically analyze incoming resumes using OpenAI, extract key skills, and classify candidates into Notion databases.',
    price: 29,
    tier: PricingTier.PAID,
    category: Category.AI_AGENTS,
    complexity: Complexity.INTERMEDIATE,
    integrations: ['OpenAI', 'Google Drive', 'Notion'],
    tags: ['HR Tech', 'AI Analysis', 'Recruiting'],
    featured: true,
    downloads: 1540
  },
  {
    id: '2',
    title: 'Stripe to Xero Reconciliation',
    description: 'Sync Stripe payouts and fees directly to Xero for seamless accounting. Includes automated Slack alerts for failed charges.',
    price: 49,
    tier: PricingTier.PAID,
    category: Category.FINANCE,
    complexity: Complexity.ADVANCED,
    integrations: ['Stripe', 'Xero', 'Slack'],
    tags: ['Accounting', 'Invoicing', 'Finance'],
    featured: true,
    downloads: 2100
  },
  {
    id: '3',
    title: 'Zillow Property Monitor',
    description: 'Monitor Zillow for new listings in specific zip codes and sync details to a Notion tracker with price change alerts.',
    price: 0,
    tier: PricingTier.FREE,
    category: Category.REAL_ESTATE,
    complexity: Complexity.INTERMEDIATE,
    integrations: ['Zillow API', 'Notion', 'Gmail'],
    tags: ['Real Estate', 'Monitoring', 'Personal Finance'],
    featured: false,
    downloads: 890
  },
  {
    id: '4',
    title: 'LinkedIn Carousel Auto-Poster',
    description: 'Create and schedule PDF carousels for LinkedIn using content from Google Sheets. Automatically repurposes Twitter threads.',
    price: 19,
    tier: PricingTier.PAID,
    category: Category.SOCIAL_MEDIA,
    complexity: Complexity.BEGINNER,
    integrations: ['LinkedIn', 'Google Sheets', 'Twitter'],
    tags: ['Social Media', 'Content Repurposing', 'Marketing'],
    featured: true,
    downloads: 3200
  },
  {
    id: '5',
    title: 'Fitbit Health Compliance',
    description: 'Aggregate weekly Fitbit activity data and generate a PDF health report sent via email for corporate wellness programs.',
    price: 0,
    tier: PricingTier.FREE,
    category: Category.HEALTHCARE,
    complexity: Complexity.INTERMEDIATE,
    integrations: ['Fitbit', 'Google Sheets', 'Gmail'],
    tags: ['Health Tech', 'Wearables', 'Reporting'],
    featured: false,
    downloads: 450
  },
  {
    id: '6',
    title: 'Incident Response Dispatcher',
    description: 'Listen to AWS CloudWatch alarms, create Jira tickets, and page on-call engineers via PagerDuty and Slack.',
    price: 0,
    tier: PricingTier.FREE,
    category: Category.SECURITY_IT,
    complexity: Complexity.ADVANCED,
    integrations: ['AWS', 'PagerDuty', 'Jira', 'Slack'],
    tags: ['DevOps', 'Incident Management', 'IT Ops'],
    featured: true,
    downloads: 1250
  },
  {
    id: '7',
    title: 'Academic Research Assistant',
    description: 'Scrape new ArXiv papers based on keywords, summarize abstract with GPT-4, and email a weekly briefing.',
    price: 0,
    tier: PricingTier.FREE,
    category: Category.RESEARCH,
    complexity: Complexity.INTERMEDIATE,
    integrations: ['ArXiv', 'OpenAI', 'SendGrid'],
    tags: ['Research', 'Education', 'Summarization'],
    featured: false,
    downloads: 980
  },
  {
    id: '8',
    title: 'Lead Enrichment Pipeline',
    description: 'Enrich HubSpot leads using Clearbit data and calculate a lead score before assigning to sales reps.',
    price: 0,
    tier: PricingTier.FREE,
    category: Category.SALES,
    complexity: Complexity.INTERMEDIATE,
    integrations: ['HubSpot', 'Clearbit', 'Salesforce'],
    tags: ['Sales Ops', 'CRM', 'Lead Gen'],
    featured: true,
    downloads: 4100
  },
  {
    id: '9',
    title: 'Zoom Meeting Summarizer',
    description: 'Transcribe Zoom recordings, generate meeting minutes and action items, and save them to your team knowledge base.',
    price: 15,
    tier: PricingTier.PAID,
    category: Category.PRODUCTIVITY,
    complexity: Complexity.INTERMEDIATE,
    integrations: ['Zoom', 'OpenAI', 'Confluence'],
    tags: ['Meetings', 'Productivity', 'Documentation'],
    featured: false,
    downloads: 2800
  },
  {
    id: '10',
    title: 'Customer Sentiment Analyzer',
    description: 'Analyze support tickets from Zendesk or Freshdesk for sentiment and escalate angry customers to management.',
    price: 39,
    tier: PricingTier.PAID,
    category: Category.SUPPORT,
    complexity: Complexity.ADVANCED,
    integrations: ['Zendesk', 'Google NLP', 'Teams'],
    tags: ['Support Ops', 'Sentiment Analysis', 'CX'],
    featured: false,
    downloads: 760
  },
  {
    id: '11',
    title: 'Shopify Inventory Sync',
    description: 'Sync inventory levels between Shopify and WooCommerce in real-time to prevent overselling.',
    price: 25,
    tier: PricingTier.PAID,
    category: Category.ECOMMERCE,
    complexity: Complexity.INTERMEDIATE,
    integrations: ['Shopify', 'WooCommerce', 'Airtable'],
    tags: ['Ecommerce', 'Inventory', 'Retail'],
    featured: true,
    downloads: 1900
  },
  {
    id: '12',
    title: 'Vector DB Indexing Pipeline',
    description: 'Ingest PDF documents from Google Drive, chunk them, embedding them, and upsert into Pinecone for RAG apps.',
    price: 0,
    tier: PricingTier.FREE,
    category: Category.AI_AGENTS,
    complexity: Complexity.ADVANCED,
    integrations: ['Google Drive', 'Pinecone', 'LangChain'],
    tags: ['RAG', 'Vector Ops', 'AI Agents'],
    featured: false,
    downloads: 650
  }
];